export const GET_ALL_GLOBAL_SPONSOR_PAGE_SUCCESS = 'GET_ALL_GLOBAL_SPONSOR_PAGE_SUCCESS';
export const GET_ALL_GLOBAL_SPONSOR_PAGE_FAIL = 'GET_ALL_GLOBAL_SPONSOR_PAGE_FAIL';

export const GET_GLOBAL_SPONSOR_TREE_SUCCESS = 'GET_GLOBAL_SPONSOR_TREE_SUCCESS';
export const GET_GLOBAL_SPONSOR_TREE_FAIL = 'GET_GLOBAL_SPONSOR_TREE_FAIL';

export const GET_GLOBAL_SPONSOR_ACCOUNT_SUCCESS = 'GET_GLOBAL_SPONSOR_ACCOUNT_SUCCESS';
export const GET_GLOBAL_SPONSOR_ACCOUNT_FAIL = 'GET_GLOBAL_SPONSOR_ACCOUNT_FAIL';

export const GET_ALL_GLOBAL_SPONSOR_SUCCESS = 'GET_ALL_GLOBAL_SPONSOR_SUCCESS';
export const GET_ALL_GLOBAL_SPONSOR_FAIL = 'GET_ALL_GLOBAL_SPONSOR_FAIL';

export const GET_GLOBAL_SPONSOR_TODAY_SUCCESS = 'GET_GLOBAL_SPONSOR_TODAY_SUCCESS';
export const GET_GLOBAL_SPONSOR_YESTERDAY_SUCCESS = 'GET_GLOBAL_SPONSOR_YESTERDAY_SUCCESS';
export const GET_GLOBAL_SPONSOR_LONG_SUCCESS = 'GET_GLOBAL_SPONSOR_LONG_SUCCESS';

export const ADD_GLOBAL_SPONSOR_SUCCESS = 'ADD_GLOBAL_SPONSOR_SUCCESS';
export const ADD_GLOBAL_SPONSOR_FAIL = 'ADD_GLOBAL_SPONSOR_FAIL';

export const EDIT_GLOBAL_SPONSOR_SUCCESS = 'EDIT_GLOBAL_SPONSOR_SUCCESS';
export const EDIT_GLOBAL_SPONSOR_FAIL = 'EDIT_GLOBAL_SPONSOR_FAIL';

export const DELETE_GLOBAL_SPONSOR_SUCCESS = 'DELETE_GLOBAL_SPONSOR_SUCCESS';
export const DELETE_GLOBAL_SPONSOR_FAIL = 'DELETE_GLOBAL_SPONSOR_FAIL';

export const RENDER_GLOBAL_SPONSOR_TO_EDIT = 'RENDER_GLOBAL_SPONSOR_TO_EDIT';

export const SHOW_GLOBAL_SPONSOR_LOADER = 'SHOW_GLOBAL_SPONSOR_LOADER';
export const REMOVE_GLOBAL_SPONSOR_LOADER = 'REMOVE_GLOBAL_SPONSOR_LOADER';