export const GET_ALL_ACCESS_SPONSOR_SUCCESS = 'GET_ALL_ACCESS_SPONSOR_SUCCESS';
export const GET_ALL_ACCESS_SPONSOR_FAIL = 'GET_ALL_ACCESS_SPONSOR_FAIL';

export const GET_ONE_ACCESS_SPONSOR_SUCCESS = 'GET_ONE_ACCESS_SPONSOR_SUCCESS';
export const GET_ONE_ACCESS_SPONSOR_FAIL = 'GET_ONE_ACCESS_SPONSOR_FAIL';

export const ADD_ONE_ACCESS_SPONSOR_SUCCESS = 'ADD_ONE_ACCESS_SPONSOR_SUCCESS';
export const ADD_ONE_ACCESS_SPONSOR_FAIL = 'ADD_ONE_ACCESS_SPONSOR_FAIL';

export const EDIT_ONE_ACCESS_SPONSOR_SUCCESS = 'EDIT_ONE_ACCESS_SPONSOR_SUCCESS';
export const EDIT_ONE_ACCESS_SPONSOR_FAIL = 'EDIT_ONE_ACCESS_SPONSOR_FAIL';

export const DELETE_ONE_ACCESS_SPONSOR_SUCCESS = 'DELETE_ONE_ACCESS_SPONSOR_SUCCESS';
export const DELETE_ONE_ACCESS_SPONSOR_FAIL = 'DELETE_ONE_ACCESS_SPONSOR_FAIL';

export const GET_PAGE_ACCESS_SPONSOR_SUCCESS="GET_PAGE_ACCESS_SPONSOR_SUCCESS";
export const GET_PAGE_ACCESS_SPONSOR_FAIL="GET_PAGE_ACCESS_SPONSOR_FAIL";