export const ADD_BUSINESS_ACCOUNT = 'ADD_BUSINESS_ACCOUNT';

export const EDIT_BUSINESS_ACCOUNT = 'EDIT_BUSINESS_ACCOUNT';

export const GET_BUSINESS_ACCOUNT = 'GET_BUSINESS_ACCOUNT';

export const REMOVE_BUSINESS_ACCOUNT= 'REMOVE_BUSINESS_ACCOUNT';

export const ADD_BUSINESS_BANK_ACCOUNT = 'ADD_BUSINESS_BANK_ACCOUNT';

export const EDIT_BUSINESS_BANK_ACCOUNT = 'EDIT_BUSINESS_BANK_ACCOUNT';

export const REMOVE_BUSINESS_BANK_ACCOUNT= 'REMOVE_BUSINESS_BANK_ACCOUNT';

export const ADD_BUSINESS_UPI_ACCOUNT = 'ADD_BUSINESS_UPI_ACCOUNT';

export const EDIT_BUSINESS_UPI_ACCOUNT = 'EDIT_BUSINESS_UPI_ACCOUNT';

export const REMOVE_BUSINESS_UPI_ACCOUNT= 'REMOVE_BUSINESS_UPI_ACCOUNT';